name: johko
title: johko's blog
theme: minima
description: I share some of my thoughts here, mainly related to Machine Learning, Computer Vision, the ML and Python communities and maybe some random thoughts here and there.
